# **Global AI, ML & Data Science Salaries**

## **ETL - Extract, Transform and Load**

Este notebook tem como objetivo realizar todo o processo de ETL, desde a ingestão, verificação de qualidade e padronização dos dados. Processo importante para as futuras análises exploratórias e visualizações.

### Fonte dos Dados

Os dados utilizados neste projeto são derivados do dataset público **"Global Salaries in AI, ML & Data Science"**, originalmente disponibilizado no Kaggle.

In [26]:
# Importando bibliotecas
import pandas as pd
import pycountry

In [27]:
# Carregando o conjunto de dados (ingestão de dados)
df = pd.read_csv('../data/salaries.csv')

In [28]:
# Exibindo as primeiras linhas do DataFrame (amostra dos dados)
df.head(10)

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2024,MI,FT,Developer,168276,USD,168276,US,0,US,M
1,2024,MI,FT,Developer,112184,USD,112184,US,0,US,M
2,2024,EN,FT,Developer,180000,USD,180000,US,0,US,M
3,2024,EN,FT,Developer,133500,USD,133500,US,0,US,M
4,2024,EN,FT,Developer,122000,USD,122000,US,0,US,M
5,2024,EN,FT,Developer,110000,USD,110000,US,0,US,M
6,2024,SE,FT,Developer,270000,USD,270000,US,0,US,M
7,2024,SE,FT,Developer,130000,USD,130000,US,0,US,M
8,2024,MI,FT,Developer,63511,USD,63511,CA,0,CA,M
9,2024,MI,FT,Developer,58092,USD,58092,CA,0,CA,M

In [29]:
# Verificando informações gerais do DataFrame (estrutura dos dados)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57194 entries, 0 to 57193
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           57194 non-null  int64
 1   experience_level    57194 non-null  object
 2   employment_type     57194 non-null  object
 3   job_title           57194 non-null  object
 4   salary              57194 non-null  int64
 5   salary_currency     57194 non-null  object
 6   salary_in_usd       57194 non-null  int64
 7   employee_residence  57194 non-null  object
 8   remote_ratio        57194 non-null  int64
 9   company_location    57194 non-null  object
 10  company_size        57194 non-null  object
dtypes: int64(4), object(7)
memory usage: 4.8+ MB

In [30]:
# Verficando o número de linhas e colunas do DataFrame
print('Total de linhas do DataFrame: ', df.shape[0])
print('Total de colunas do DataFrame: ', df.shape[1])

Total de linhas do DataFrame:  57194
Total de colunas do DataFrame:  11

In [31]:
# Listando os nomes das colunas do DataFrame (schema dos dados)
df.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

In [32]:
# Verificando os tipos de dados de cada coluna
df.dtypes

work_year              int64
experience_level      object
employment_type       object
job_title             object
salary                 int64
salary_currency       object
salary_in_usd          int64
employee_residence    object
remote_ratio           int64
company_location      object
company_size          object
dtype: object

🎯 O DataFrame possui valores apenas do tipo String e Int.

In [33]:
# Estatísticas descritivas do DataFrame (estatística básica) -> Mostra estatísticas descritivas para colunas numéricas
df.describe()

          work_year        salary  salary_in_usd  remote_ratio
count  57194.000000  5.719400e+04   57194.000000  57194.000000
mean    2023.776305  1.641818e+05  159223.565829     22.211246
std        0.519883  2.060327e+05   72155.164297     41.424262
min     2020.000000  1.400000e+04   15000.000000      0.000000
25%     2024.000000  1.094000e+05  109300.000000      0.000000
50%     2024.000000  1.495520e+05  149040.000000      0.000000
75%     2024.000000  2.000000e+05  200000.000000      0.000000
max     2024.000000  3.040000e+07  800000.000000    100.000000

In [34]:
# Verificando se há valores nulos no DataFrame (qualidade dos dados)
df.isnull().sum()

work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

🎯 Não há valores nulos no DataFrame.

In [35]:
# Verificando quais são valores únicos da coluna 'remote_ratio'
df['remote_ratio'].unique()

# 0 - trabalhos presenciais
# 100 - trabalhos remotos
# 50 - trabalhos híbridos

array([  0, 100,  50])

In [36]:
# Mapeando os valores de 'remote_ratio' para português, pois eles estão em códigos. Isso ajudará na análise e visualização dos dados.
remote_map = {
    0: 'Presencial',
    50: 'Híbrido',
    100: 'Remoto'
}

df['remote_ratio_pt'] = df['remote_ratio'].map(remote_map)
df['remote_ratio_pt'].unique()

array(['Presencial', 'Remoto', 'Híbrido'], dtype=object)

In [37]:
# Verificando quais são valores únicos da coluna 'experience_level'
df['experience_level'].unique()

array(['MI', 'EN', 'SE', 'EX'], dtype=object)

In [38]:
# Mapeando os valores de 'experience_level' para português, pois os cargos estão classificados por abreviações em inglês. Isso ajudará na análise e visualização dos dados.
experience_map = {
    'EN': 'Júnior',
    'MI': 'Pleno',
    'SE': 'Sênior',
    'EX': 'Executivo'
}

df['experience_level_pt'] = df['experience_level'].map(experience_map)
df['experience_level_pt'].unique()

array(['Pleno', 'Júnior', 'Sênior', 'Executivo'], dtype=object)

In [39]:
# Verificando quais são valores únicos da coluna 'employment_type'
df['employment_type'].unique()

array(['FT', 'PT', 'CT', 'FL'], dtype=object)

In [40]:
# Mapeando os valores de 'employment_type' para português, pois os contratos estão classificados por abreviações em inglês. Isso ajudará na análise e visualização dos dados.
employment_map = {
    'FT': 'Tempo Integral',
    'PT': 'Meio Período',
    'CT': 'Contrato',
    'FL': 'Freelancer'
}

df['employment_type_pt'] = df['employment_type'].map(employment_map)
df['employment_type_pt'].unique()

array(['Tempo Integral', 'Meio Período', 'Contrato', 'Freelancer'],
      dtype=object)

In [41]:
# Verificando quais são valores únicos da coluna 'company_size'
df['company_size'].unique()

array(['M', 'L', 'S'], dtype=object)

In [42]:
# Mapeando os valores de 'company_size' para português, pois os tamanhos estão classificados por abreviações em inglês. Isso ajudará na análise e visualização dos dados.
company_size_map = {
    'S': 'Pequena',
    'M': 'Média',
    'L': 'Grande'
}

df['company_size_pt'] = df['company_size'].map(company_size_map)
df['company_size_pt'].unique()

array(['Média', 'Grande', 'Pequena'], dtype=object)

In [43]:
# Criando uma nova coluna com o salário em milhares de dólares (K USD = mil dólares) para melhorar a visualização dos dados
df["salary_usd_k"] = df["salary_in_usd"] / 1000

In [44]:
# Função para converter ISO-2 para ISO-3
def iso2_to_iso3(code):
    try:
        return pycountry.countries.get(alpha_2=code).alpha_3
    except:
        return None

In [45]:
if 'employee_residence' in df.columns:
    df['residence_iso3'] = df['employee_residence'].apply(iso2_to_iso3)

In [46]:
# Verificando se as novas colunas criadas foram adicionadas corretamente ao DataFrame
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,remote_ratio_pt,experience_level_pt,employment_type_pt,company_size_pt,salary_usd_k,residence_iso3
0,2024,MI,FT,Developer,168276,USD,168276,US,0,US,M,Presencial,Pleno,Tempo Integral,Média,168.276,USA
1,2024,MI,FT,Developer,112184,USD,112184,US,0,US,M,Presencial,Pleno,Tempo Integral,Média,112.184,USA
2,2024,EN,FT,Developer,180000,USD,180000,US,0,US,M,Presencial,Júnior,Tempo Integral,Média,180.000,USA
3,2024,EN,FT,Developer,133500,USD,133500,US,0,US,M,Presencial,Júnior,Tempo Integral,Média,133.500,USA
4,2024,EN,FT,Developer,122000,USD,122000,US,0,US,M,Presencial,Júnior,Tempo Integral,Média,122.000,USA

🎯 Hora de salvar o DataFrame com as novas colunas e correções em um novo CSV para a etapa de Análise Exploratória!

In [47]:
# Salvando o DataFrame limpo em um novo arquivo CSV
df.to_csv("../data/salaries_clean.csv", index=False)